### ISSUE TITLE
python 3.12 breaks waterkit

### ISSUE THREAD

**Issue by blakemertz** [forlilab/waterkit#12]
Just an FYI to waterkit users -- I just installed waterkit using the installation instructions, but my conda environment pulled python 3.12.1. 3.12 dropped support for the imp module and so until that issue is resolved within your codebase, you need to restrict the python version to be <= 3.11: [https://stackoverflow.com/questions/77274572/multiqc-modulenotfounderror-no-module-named-imp](url)

I was getting the following error when trying to run wk_prepare_receptor.py:

```
python /media/bak11/binaries/git/waterkit/scripts/wk_prepare_receptor.py -i MDH-258_molrep7_refmac3-coot-0.pdb -o MDH-258-xtal_prepared --pdb --amber_pdbqt
Traceback (most recent call last):
  File "/media/bak11/binaries/git/waterkit/scripts/wk_prepare_receptor.py", line 20, in <module>
    from waterkit import utils
  File "/media/bak11/binaries/git/waterkit/waterkit/__init__.py", line 8, in <module>
    from .autogrid import AutoGrid
  File "/media/bak11/binaries/git/waterkit/waterkit/autogrid.py", line 16, in <module>
    from .molecule import Molecule
  File "/media/bak11/binaries/git/waterkit/waterkit/molecule.py", line 9, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

Specifying python=3.11 when creating the environment fixed the issue.

**Comment by jeeberhardt** [comment]
Thanks! Will fix that as soon as possible!
